import { boolean, index, int, json, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

/** Identity remains compatible with Manus OAuth; CSPP permissions and verification are modeled separately. */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }),
  // Authentification locale par mot de passe (hash bcrypt). Nul pour les comptes créés uniquement via un flux externe.
  passwordHash: varchar("passwordHash", { length: 255 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  accountStatus: mysqlEnum("accountStatus", ["pending_verification", "verified", "rejected", "suspended", "deactivated"]).default("pending_verification").notNull(),
  emailVerifiedAt: timestamp("emailVerifiedAt"), verifiedAt: timestamp("verifiedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
}, (table) => [index("users_status_idx").on(table.accountStatus), uniqueIndex("users_email_unique").on(table.email)]);

export const promotions = mysqlTable("promotions", { id: int("id").autoincrement().primaryKey(), year: int("year").notNull().unique(), label: varchar("label", { length: 120 }), isActive: boolean("isActive").default(true).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const alumniProfiles = mysqlTable("alumniProfiles", { userId: int("userId").primaryKey().references(() => users.id, { onDelete: "cascade" }), promotionId: int("promotionId").references(() => promotions.id), firstName: varchar("firstName", { length: 100 }), lastName: varchar("lastName", { length: 100 }), headline: varchar("headline", { length: 180 }), organization: varchar("organization", { length: 180 }), jobTitle: varchar("jobTitle", { length: 180 }), bio: text("bio"), location: varchar("location", { length: 120 }), avatarStorageKey: varchar("avatarStorageKey", { length: 512 }), directoryVisibility: mysqlEnum("directoryVisibility", ["network", "promotion_only", "private"]).default("network").notNull(), mentorAvailable: boolean("mentorAvailable").default(false).notNull(), mentorTopics: json("mentorTopics"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (table) => [index("profiles_promotion_idx").on(table.promotionId), index("profiles_mentor_idx").on(table.mentorAvailable)]);

export const roles = mysqlTable("roles", { id: int("id").autoincrement().primaryKey(), code: mysqlEnum("code", ["alumni", "mentor", "moderator", "administrator"]).notNull().unique(), label: varchar("label", { length: 80 }).notNull() });
export const userRoles = mysqlTable("userRoles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), roleId: int("roleId").notNull().references(() => roles.id), assignedBy: int("assignedBy").references(() => users.id), assignedAt: timestamp("assignedAt").defaultNow().notNull(), revokedAt: timestamp("revokedAt"), reason: varchar("reason", { length: 500 }) }, (table) => [uniqueIndex("user_role_unique").on(table.userId, table.roleId), index("user_roles_user_idx").on(table.userId)]);

export const verificationRequests = mysqlTable("verificationRequests", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), status: mysqlEnum("status", ["submitted", "needs_information", "approved", "rejected"]).default("submitted").notNull(), decisionReason: text("decisionReason"), reviewedBy: int("reviewedBy").references(() => users.id), submittedAt: timestamp("submittedAt").defaultNow().notNull(), reviewedAt: timestamp("reviewedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [index("verification_queue_idx").on(table.status, table.submittedAt), index("verification_user_idx").on(table.userId)]);
export const verificationDocuments = mysqlTable("verificationDocuments", { id: int("id").autoincrement().primaryKey(), verificationRequestId: int("verificationRequestId").notNull().references(() => verificationRequests.id, { onDelete: "cascade" }), storageKey: varchar("storageKey", { length: 512 }).notNull(), originalName: varchar("originalName", { length: 255 }).notNull(), mimeType: varchar("mimeType", { length: 100 }).notNull(), uploadedAt: timestamp("uploadedAt").defaultNow().notNull() });

export const connections = mysqlTable("connections", { id: int("id").autoincrement().primaryKey(), userAId: int("userAId").notNull().references(() => users.id, { onDelete: "cascade" }), userBId: int("userBId").notNull().references(() => users.id, { onDelete: "cascade" }), initiatedById: int("initiatedById").notNull().references(() => users.id, { onDelete: "cascade" }), status: mysqlEnum("status", ["pending", "accepted", "declined", "blocked"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), respondedAt: timestamp("respondedAt") }, (table) => [uniqueIndex("connection_pair_unique").on(table.userAId, table.userBId), index("connection_recipient_idx").on(table.userBId, table.status)]);

export const conversations = mysqlTable("conversations", { id: int("id").autoincrement().primaryKey(), kind: mysqlEnum("kind", ["direct", "group"]).default("direct").notNull(), directPairKey: varchar("directPairKey", { length: 40 }).unique(), title: varchar("title", { length: 160 }), createdBy: int("createdBy").notNull().references(() => users.id), createdAt: timestamp("createdAt").defaultNow().notNull(), lastMessageAt: timestamp("lastMessageAt"), archivedAt: timestamp("archivedAt") }, (table) => [index("conversation_recent_idx").on(table.lastMessageAt)]);
export const conversationMembers = mysqlTable("conversationMembers", { conversationId: int("conversationId").notNull().references(() => conversations.id, { onDelete: "cascade" }), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), joinedAt: timestamp("joinedAt").defaultNow().notNull(), leftAt: timestamp("leftAt"), lastReadMessageId: int("lastReadMessageId"), mutedAt: timestamp("mutedAt") }, (table) => [uniqueIndex("conversation_member_unique").on(table.conversationId, table.userId), index("conversation_member_user_idx").on(table.userId)]);
export const messages = mysqlTable("messages", { id: int("id").autoincrement().primaryKey(), conversationId: int("conversationId").notNull().references(() => conversations.id, { onDelete: "cascade" }), senderId: int("senderId").notNull().references(() => users.id), body: text("body"), kind: mysqlEnum("kind", ["text", "attachment", "voice", "system"]).default("text").notNull(), replyToId: int("replyToId"), sentAt: timestamp("sentAt").defaultNow().notNull(), editedAt: timestamp("editedAt"), deletedAt: timestamp("deletedAt") }, (table) => [index("messages_thread_idx").on(table.conversationId, table.sentAt), index("messages_sender_idx").on(table.senderId, table.sentAt)]);
export const messageAttachments = mysqlTable("messageAttachments", { id: int("id").autoincrement().primaryKey(), messageId: int("messageId").notNull().references(() => messages.id, { onDelete: "cascade" }), storageKey: varchar("storageKey", { length: 512 }).notNull(), originalName: varchar("originalName", { length: 255 }).notNull(), mimeType: varchar("mimeType", { length: 100 }).notNull(), sizeBytes: int("sizeBytes").notNull(), durationMs: int("durationMs"), thumbnailKey: varchar("thumbnailKey", { length: 512 }), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [index("message_attachment_idx").on(table.messageId), uniqueIndex("storage_key_unique").on(table.storageKey)]);
export const auditLogs = mysqlTable("auditLogs", { id: int("id").autoincrement().primaryKey(), actorId: int("actorId").references(() => users.id), actorRole: varchar("actorRole", { length: 32 }), action: varchar("action", { length: 120 }).notNull(), entityType: varchar("entityType", { length: 80 }).notNull(), entityId: varchar("entityId", { length: 80 }).notNull(), reason: text("reason"), before: json("before"), after: json("after"), requestId: varchar("requestId", { length: 80 }), ipHash: varchar("ipHash", { length: 128 }), occurredAt: timestamp("occurredAt").defaultNow().notNull() }, (table) => [index("audit_entity_idx").on(table.entityType, table.entityId), index("audit_actor_idx").on(table.actorId, table.occurredAt)]);

// --- Fil de publications (domaine "Publications et commentaires") ---
export const posts = mysqlTable("posts", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull().references(() => users.id, { onDelete: "cascade" }), body: text("body").notNull(), visibility: mysqlEnum("visibility", ["network", "promotion_only", "public"]).default("network").notNull(), attachmentStorageKey: varchar("attachmentStorageKey", { length: 512 }), createdAt: timestamp("createdAt").defaultNow().notNull(), editedAt: timestamp("editedAt"), hiddenAt: timestamp("hiddenAt"), hiddenReason: varchar("hiddenReason", { length: 500 }), deletedAt: timestamp("deletedAt") }, (table) => [index("posts_feed_idx").on(table.createdAt), index("posts_author_idx").on(table.authorId)]);
export const postComments = mysqlTable("postComments", { id: int("id").autoincrement().primaryKey(), postId: int("postId").notNull().references(() => posts.id, { onDelete: "cascade" }), authorId: int("authorId").notNull().references(() => users.id, { onDelete: "cascade" }), body: text("body").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), hiddenAt: timestamp("hiddenAt"), deletedAt: timestamp("deletedAt") }, (table) => [index("comments_post_idx").on(table.postId, table.createdAt)]);
export const postReactions = mysqlTable("postReactions", { id: int("id").autoincrement().primaryKey(), postId: int("postId").notNull().references(() => posts.id, { onDelete: "cascade" }), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), kind: mysqlEnum("kind", ["like", "celebrate", "support", "insightful"]).default("like").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [uniqueIndex("reaction_unique").on(table.postId, table.userId)]);
export const savedItems = mysqlTable("savedItems", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), itemType: mysqlEnum("itemType", ["post", "opportunity", "event", "project"]).notNull(), itemId: int("itemId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [uniqueIndex("saved_item_unique").on(table.userId, table.itemType, table.itemId)]);

// --- Signalements (modération) ---
export const reports = mysqlTable("reports", { id: int("id").autoincrement().primaryKey(), reporterId: int("reporterId").notNull().references(() => users.id, { onDelete: "cascade" }), targetType: mysqlEnum("targetType", ["post", "comment", "message", "profile", "opportunity", "event", "project"]).notNull(), targetId: int("targetId").notNull(), reason: varchar("reason", { length: 120 }).notNull(), details: text("details"), status: mysqlEnum("status", ["open", "under_review", "escalated", "resolved", "dismissed"]).default("open").notNull(), decision: varchar("decision", { length: 60 }), decisionReason: text("decisionReason"), handledBy: int("handledBy").references(() => users.id), createdAt: timestamp("createdAt").defaultNow().notNull(), resolvedAt: timestamp("resolvedAt") }, (table) => [index("reports_status_idx").on(table.status, table.createdAt), index("reports_target_idx").on(table.targetType, table.targetId)]);

// --- Opportunités ---
export const opportunities = mysqlTable("opportunities", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 180 }).notNull(), type: mysqlEnum("type", ["job", "internship", "freelance", "volunteering", "other"]).default("other").notNull(), organization: varchar("organization", { length: 180 }), location: varchar("location", { length: 120 }), description: text("description").notNull(), applyUrl: varchar("applyUrl", { length: 500 }), contactEmail: varchar("contactEmail", { length: 320 }), status: mysqlEnum("status", ["pending", "published", "expired", "rejected", "archived"]).default("pending").notNull(), moderationReason: text("moderationReason"), closesAt: timestamp("closesAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), publishedAt: timestamp("publishedAt") }, (table) => [index("opportunities_status_idx").on(table.status, table.createdAt)]);

// --- Événements ---
export const events = mysqlTable("events", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 180 }).notNull(), description: text("description").notNull(), location: varchar("location", { length: 200 }), isOnline: boolean("isOnline").default(false).notNull(), startsAt: timestamp("startsAt").notNull(), endsAt: timestamp("endsAt"), capacity: int("capacity"), status: mysqlEnum("status", ["pending", "published", "cancelled", "archived"]).default("pending").notNull(), moderationReason: text("moderationReason"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [index("events_status_idx").on(table.status, table.startsAt)]);
export const eventRegistrations = mysqlTable("eventRegistrations", { id: int("id").autoincrement().primaryKey(), eventId: int("eventId").notNull().references(() => events.id, { onDelete: "cascade" }), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), status: mysqlEnum("status", ["registered", "cancelled", "waitlisted"]).default("registered").notNull(), registeredAt: timestamp("registeredAt").defaultNow().notNull() }, (table) => [uniqueIndex("event_registration_unique").on(table.eventId, table.userId)]);

// --- Mentorat ---
export const mentorshipRequests = mysqlTable("mentorshipRequests", { id: int("id").autoincrement().primaryKey(), menteeId: int("menteeId").notNull().references(() => users.id, { onDelete: "cascade" }), mentorId: int("mentorId").notNull().references(() => users.id, { onDelete: "cascade" }), topic: varchar("topic", { length: 200 }).notNull(), message: text("message"), status: mysqlEnum("status", ["pending", "accepted", "declined", "completed", "cancelled"]).default("pending").notNull(), scheduledAt: timestamp("scheduledAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), respondedAt: timestamp("respondedAt") }, (table) => [index("mentorship_mentor_idx").on(table.mentorId, table.status), index("mentorship_mentee_idx").on(table.menteeId, table.status)]);

// --- Projets et groupes ---
export const projects = mysqlTable("projects", { id: int("id").autoincrement().primaryKey(), ownerId: int("ownerId").notNull().references(() => users.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), description: text("description"), visibility: mysqlEnum("visibility", ["network", "promotion_only", "private"]).default("network").notNull(), status: mysqlEnum("status", ["active", "archived"]).default("active").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const projectMembers = mysqlTable("projectMembers", { projectId: int("projectId").notNull().references(() => projects.id, { onDelete: "cascade" }), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), role: mysqlEnum("role", ["owner", "member"]).default("member").notNull(), joinedAt: timestamp("joinedAt").defaultNow().notNull() }, (table) => [uniqueIndex("project_member_unique").on(table.projectId, table.userId)]);

// --- Notifications et communications officielles ---
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }), type: varchar("type", { length: 60 }).notNull(), title: varchar("title", { length: 200 }).notNull(), body: text("body"), link: varchar("link", { length: 300 }), readAt: timestamp("readAt"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => [index("notifications_user_idx").on(table.userId, table.readAt, table.createdAt)]);
export const campaigns = mysqlTable("campaigns", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 200 }).notNull(), body: text("body").notNull(), segment: mysqlEnum("segment", ["all", "verified", "mentors", "promotion"]).default("all").notNull(), promotionId: int("promotionId").references(() => promotions.id), status: mysqlEnum("status", ["draft", "sent"]).default("draft").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), sentAt: timestamp("sentAt") });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;
export type Post = typeof posts.$inferSelect;
export type Opportunity = typeof opportunities.$inferSelect;
export type Event = typeof events.$inferSelect;
export type MentorshipRequest = typeof mentorshipRequests.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
